basePath: /
definitions:
  auth.ModelRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  auth.ModelResponse:
    properties:
      token:
        type: string
    type: object
  data.StatusResponse:
    properties:
      status:
        type: string
    type: object
  data.Write:
    properties:
      data:
        additionalProperties: true
        type: object
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для tarantool
  title: Tarantool API
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Вход в систему
      operationId: login
      parameters:
      - description: auth info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.ModelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.ModelResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Login
      tags:
      - login
  /api/write:
    post:
      consumes:
      - application/json
      description: Запись данных
      operationId: data-write
      parameters:
      - description: write data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.Write'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/data.StatusResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Wite
      tags:
      - data
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
